import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { RouterProvider, createRouter } from "@tanstack/react-router";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { routeTree } from "./routeTree.gen"; // auto-generated by the Vite plugin
import "./index.css";

const router = createRouter({
  routeTree,
  // Start loading a page's code when the user HOVERS a link, not when they click.
  // One of the easiest perceived-speed wins there is.
  defaultPreload: "intent",
  scrollRestoration: true,
});

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      // Product data doesn't change every second. Keep it "fresh" for 1 minute
      // so navigating back and forth doesn't refetch everything.
      staleTime: 60 * 1000,
    },
  },
});

createRoot(document.getElementById("root")).render(
  <StrictMode>
    <QueryClientProvider client={queryClient}>
      <RouterProvider router={router} />
    </QueryClientProvider>
  </StrictMode>,
);
